environment:
  ANDROID_HOME: C:\Program Files (x86)\Android\android-sdk

install:
  - echo y | "%ANDROID_HOME%\tools\android.bat" --silent update sdk --no-ui --all --filter android-21
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t build-tools-23.0.1

test_script:
  - gradlew.bat build

build: off